name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set environment variables
      run: | 
        export GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)
        export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
    - uses: actions/setup-node@v1
      name: Node.js
      with:
        node-version: 16 
    - name: Build
      run: |
        yarn build
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Docker Push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: "${{ needs.build.outputs.dockerhub_username }}/example-mock:${{ needs.build.outputs.github_sha_short }}"