name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.set_sha.outputs.GITHUB_SHA_SHORT }}
    steps:
    - uses: actions/checkout@v2
    - id: set_sha
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_OUTPUT

    - uses: actions/setup-node@v1
      name: Node.js
      with:
        node-version: 16

    - name: Build
      run: yarn build

    - uses: actions/upload-artifact@master
      with:
        name: dist-build
        path: dist

    - uses: actions/upload-artifact@master
      with:
        name: package-json
        path: package.json

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: dist-build
        path: dist
    - name: check-dist
      run: ls dist

    - uses: actions/download-artifact@master
      with:
        name: package-json
        path: package.json

    - name: Yarn
      run: yarn && yarn add forever

    - name: Start
      env:
        STATE_FILE: /state.json
      run: forever start /dist/index.js

    - name: Stop
      run: forever stop /dist/index.js

  # push:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v2
    
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2

  #   - uses: actions/download-artifact@master
  #     with:
  #       name: dist-build
  #       path: dist
  #   - name: check-dist
  #     run: ls dist

  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # - name: Docker Push
    #   uses: docker/build-push-action@v3
    #   env:
    #     DOCKERHUB_USERNAME: '${{ secrets.DOCKERHUB_USERNAME }}'
    #   with:
    #     context: .
    #     push: true
    #     tags: "${{ env.DOCKERHUB_USERNAME }}/example-mock:${{ needs.build.outputs.sha_short }}"