name: Reusable workflow example test

on:
  workflow_call:
    outputs:
      sha-ref:
        description: "Sha short ref"
        value: ${{ jobs.set-sha-short-ref.outputs.sha_short }}

jobs:
  set-sha-short-ref:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.set_sha.outputs.GITHUB_SHA_SHORT }}
    steps:
    - uses: actions/checkout@v3
    - id: set_sha
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_OUTPUT

  check-required-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: "check is DOCKERHUB_USERNAME exists"
      env: 
          super_secret: ${{ secrets.DOCKERHUB_USERNAMExxx }}
      if: ${{ env.super_secret == '' }}
      run: echo "echo the secret \"DOCKERHUB_USERNAME\" has not been made; echo please go to \"settings \> secrets \> actions\" to create it" && exit 1

    - name: "check is DOCKERHUB_TOKEN exists"
      env: 
          super_secret: ${{ secrets.DOCKERHUB_TOKEN }}
      if: ${{ env.super_secret == '' }}
      run: echo "echo the secret \"DOCKERHUB_UTOKEN\" has not been made; echo please go to \"settings \> secrets \> actions\" to create it" && exit 1